conduct_comments = {
    1: [
        "{0} consistently demonstrates good conduct, though occasional reminders are needed to stay on track.",
        "{0} generally displays good behavior, but may sometimes require gentle redirection to stay focused.",
        "{0} usually follows classroom rules and shows respect for peers and teachers.",
        "{0} demonstrates good conduct but occasionally needs reminders to maintain consistency.",
        "{0} generally exhibits good behavior and manners but may need occasional guidance to stay on track.",
        "{0} consistently shows improvement in conduct and responds well to feedback and guidance.",
        "{0} is generally respectful and responsible but may need occasional reminders to stay focused.",
        "{0} usually displays good conduct, though there is room for improvement in consistency and self-discipline.",
        "{0} is a positive role model in class, consistently demonstrating good behavior and respect for others.",
        "{0} exhibits strong self-discipline and consistently follows classroom expectations.",
        "{0} is always respectful and responsible, contributing positively to the classroom environment.",
        "{0} displays a mature attitude toward following rules and staying focused in class.",
        "{0} consistently maintains good conduct and creates a positive atmosphere for peers.",
        "{0} is very dependable in terms of conduct and always strives to make the right choices.",
        "{0} sets a great example for others with excellent behavior and respect for the class.",
        "{0} is attentive and well-behaved, showing a strong sense of responsibility in all tasks.",
        "{0} consistently demonstrates a respectful attitude and maintains a positive attitude toward peers and teachers.",
        "{0} shows great attention to detail and responsibility in following classroom rules.",
        "{0} is an exemplary student in terms of behavior and consistently contributes to a positive classroom atmosphere.",
        "{0} displays strong self-control and consistently sets a good example for others.",
        "{0} handles responsibility well and always follows through with assigned tasks.",
        "{0} consistently makes good choices and follows classroom expectations without reminders.",
        "{0} has a strong sense of personal responsibility and always acts in a respectful manner.",
        "{0} is a model student who consistently demonstrates integrity and good behavior."
    ],
    2: [
        "{0} demonstrates satisfactory conduct but may occasionally require reminders to adhere to classroom expectations.",
        "{0} shows improvement in conduct but may still need consistent guidance to maintain appropriate behavior.",
        "{0} generally meets conduct expectations but may need occasional support to stay focused.",
        "{0} demonstrates satisfactory behavior but could benefit from more consistent adherence to classroom rules.",
        "{0} exhibits acceptable conduct but may need reminders to consistently follow school rules and procedures.",
        "{0} shows effort in maintaining satisfactory conduct but may need additional support in certain situations.",
        "{0} meets basic conduct expectations but may need occasional reminders to demonstrate more consistent behavior.",
        "{0} generally follows classroom rules but could improve in showing more initiative and self-control.",
        "{0} demonstrates adequate conduct and follows directions but may require additional reminders on occasion.",
        "{0} usually behaves appropriately, but there are times when more focus and attention are needed.",
        "{0} generally adheres to classroom rules, but more consistency is needed to stay on task.",
        "{0} is generally respectful but may need occasional redirection to maintain focus during class.",
        "{0} demonstrates acceptable behavior, though there are moments where additional guidance may be needed.",
        "{0} generally meets expectations, but occasional lapses in focus may require gentle correction.",
        "{0} often participates appropriately, but can sometimes be distracted or disengaged.",
        "{0} shows positive behavior overall, but could benefit from more consistent effort in staying focused.",
        "{0} generally follows classroom guidelines but sometimes needs additional support to stay on task.",
        "{0} is polite and respectful, but occasional reminders are needed to maintain focus.",
        "{0} demonstrates satisfactory behavior, although consistent attention to classroom expectations would benefit them.",
        "{0} displays good behavior overall, but may need to work on maintaining focus in group activities.",
        "{0} generally adheres to rules, but there are moments when additional guidance is needed.",
        "{0} usually behaves appropriately, but requires occasional reminders to stay on task.",
        "{0} displays a cooperative attitude but may need to work on consistency in meeting expectations.",
        "{0} follows the rules but sometimes needs more encouragement to stay engaged during lessons."
    ],
    3: [
        "{0} often struggles to meet conduct expectations and requires frequent reminders to follow classroom rules.",
        "{0} consistently exhibits behavior that disrupts the learning environment and requires significant redirection.",
        "{0} frequently disregards classroom rules and requires consistent intervention to address behavioral issues.",
        "{0} displays disruptive behavior that negatively impacts peers and requires immediate attention and support.",
        "{0} consistently demonstrates poor conduct and requires a comprehensive behavior intervention plan.",
        "{0} often exhibits disrespectful behavior towards peers and teachers and requires intensive behavior support.",
        "{0} struggles to maintain appropriate conduct and requires ongoing support to develop better self-discipline.",
        "{0} consistently demonstrates behavior that is not conducive to a positive learning environment and requires urgent intervention and support.",
        "{0} frequently struggles with staying on task and requires frequent redirection to remain focused.",
        "{0} often disrupts the class and requires regular intervention to refocus on tasks.",
        "{0} displays challenging behavior that interferes with the learning environment and needs ongoing support.",
        "{0} continues to have difficulty following the rules, and improvement is necessary for a more productive learning experience.",
        "{0} often disregards classroom expectations, impacting the overall classroom dynamic.",
        "{0} frequently needs assistance in making positive behavior choices and staying on task.",
        "{0} regularly exhibits disruptive behavior, and more consistent behavior management is needed.",
        "{0} struggles to meet the classroom conduct standards and requires ongoing support and intervention.",
        "{0} needs frequent redirection and often disrupts the class, impacting their own learning and others'.",
        "{0} needs consistent intervention to follow rules and remain focused during lessons.",
        "{0} displays inconsistent behavior and needs more support to follow the class expectations.",
        "{0} regularly engages in off-task behavior and requires guidance to stay focused.",
        "{0} struggles with behavior management and often needs assistance to re-engage in learning.",
        "{0} has difficulty following classroom rules, often requiring individual attention to improve behavior.",
        "{0} demonstrates behavior that disrupts learning, and significant improvements are needed for a positive classroom environment."
    ]
}
