english_comments = {
    1: [
        "{0} consistently demonstrates exceptional writing skills and a deep understanding of literary concepts.",
        "{0} excels in reading comprehension and consistently produces insightful analyses.",
        "{0} has an outstanding vocabulary and grammar usage, enhancing written work significantly.",
        "{0} has a strong grasp of complex texts and contributes thoughtfully to class discussions.",
        "{0} is imaginative and well-structured creative writing, showcasing advanced skills.",
        "{0} consistently exceeds expectations in reading, writing, and critical thinking.",
        "{0} demonstrates superior command of the English language, both in writing and orally.",
        "{0} has exceptional analytical skills and ability to interpret texts.",
        "{0} consistently produces high-quality essays and displays excellent attention to detail.",
        "{0} demonstrates a deep understanding of literature and communicates ideas effectively.",
        "{0} consistently demonstrates a high level of critical thinking in both written and verbal expressions.",
        "{0} shows a deep and impressive understanding of all aspects of English, from grammar to creative writing.",
        "{0} consistently applies advanced literary techniques in writing assignments, elevating the quality of their work.",
        "{0} excels in analyzing complex texts and provides detailed, well-supported arguments in discussions.",
        "{0} regularly produces creative and innovative essays, showcasing a deep understanding of the material.",
        "{0} has mastered advanced vocabulary and grammar, consistently improving the quality of written work.",
        "{0} is a skilled writer, demonstrating excellence in both fiction and non-fiction assignments.",
        "{0} continually demonstrates excellent problem-solving skills when interpreting difficult literary material."
    ],
    2: [
        "{0} meets grade-level expectations and participates actively in class discussions.",
        "{0} demonstrates good comprehension skills and produces solid written work.",
        "{0} shows a clear understanding of the material and completes assignments accurately.",
        "{0} effectively uses grammar and vocabulary appropriate for their grade level.",
        "{0} participates in class and consistently meets writing and reading goals.",
        "{0} has a good grasp of literary concepts and applies them well in assignments.",
        "{0} completes reading assignments on time and shows understanding in discussions.",
        "{0} writes clear and coherent essays, demonstrating understanding of the topics.",
        "{0} shows steady progress in reading and writing skills.",
        "{0} meets the standard expectations for reading comprehension and written expression.",
        "{0} demonstrates a solid understanding of English concepts and continues to show growth in writing skills.",
        "{0} produces thoughtful responses to reading material and consistently meets expectations in assignments.",
        "{0} consistently applies learned concepts to written work, showing a good level of comprehension and analysis.",
        "{0} effectively uses grade-level vocabulary and demonstrates solid writing skills in both creative and analytical work.",
        "{0} approaches assignments with a positive attitude and consistently completes work on time.",
        "{0} is able to explain the main ideas of complex texts and provides coherent written responses.",
        "{0} completes assignments with attention to detail, although some minor revisions are needed to enhance clarity.",
        "{0} shows steady progress in writing and comprehension, making noticeable improvements throughout the term."
    ],
    3: [
        "{0} needs to improve reading comprehension and participate more in class discussions.",
        "{0} struggles with writing clarity and needs to focus on grammar and vocabulary.",
        "{0} requires additional support to understand and analyze texts effectively.",
        "{0} should work on completing assignments on time and improving the quality of written work.",
        "{0} needs to engage more with the reading material and seek help when needed.",
        "{0} has difficulty understanding complex texts and needs to ask questions in class.",
        "{0} should focus on improving writing structure and coherence.",
        "{0} requires more practice in reading comprehension to meet grade-level expectations.",
        "{0} needs to participate more in class to enhance understanding of the material.",
        "{0} should work on organizing ideas more clearly in writing assignments.",
        "{0} continues to face challenges with reading comprehension and requires frequent support during assignments.",
        "{0} struggles with expressing ideas clearly in writing and would benefit from focusing on sentence structure.",
        "{0} needs to improve reading comprehension skills and participate more actively in class discussions.",
        "{0} should dedicate more time to reading the material carefully and working on sentence fluency in writing.",
        "{0} requires additional practice with basic writing skills, particularly in grammar and organization.",
        "{0} needs help in focusing on key concepts in reading and may benefit from additional explanation or tutoring.",
        "{0} continues to struggle with reading comprehension and needs further development in critical thinking skills.",
        "{0} should focus on improving writing structure, coherence, and clarity in assignments."
    ]
}