history_comments = {
    1: [
        "{0} shows exceptional understanding of historical events and their significance.",
        "{0} excels in critical thinking and consistently provides insightful analyses of social studies topics.",
        "{0} demonstrates a deep knowledge of geography and its impact on historical events.",
        "{0} consistently makes connections between historical events and current issues.",
        "{0} shows superior understanding of civic concepts and actively participates in discussions.",
        "{0} excels in analyzing primary sources and drawing meaningful conclusions.",
        "{0} demonstrates a strong grasp of social, economic, and political systems.",
        "{0} consistently exceeds expectations in understanding and presenting social studies content.",
        "{0} demonstrates an exceptional ability to synthesize historical information and apply it to current global issues.",
        "{0} consistently offers profound insights during class discussions and shows leadership in understanding historical trends.",
        "{0} excels in examining the broader implications of historical events on contemporary society.",
        "{0} demonstrates a sophisticated understanding of the intersection between geography, politics, and history.",
        "{0} consistently produces high-quality research projects that reflect a deep understanding of historical contexts.",
        "{0} demonstrates superior skills in analyzing the causes and effects of historical events and their lasting impact.",
        "{0} excels in drawing connections between historical events and their social, cultural, and economic influences.",
        "{0} consistently demonstrates mastery of historical content and is able to apply concepts in complex, real-world scenarios."
    ],
    2: [
        "{0} meets grade-level expectations and participates actively in social studies discussions.",
        "{0} demonstrates good understanding of historical events and their contexts.",
        "{0} completes assignments accurately and shows a clear understanding of the material.",
        "{0} effectively uses maps and resources to understand geographic concepts.",
        "{0} shows a good grasp of civic concepts and applies them in discussions.",
        "{0} completes projects on time and demonstrates understanding of social studies topics.",
        "{0} writes coherent essays and shows good understanding of historical contexts.",
        "{0} consistently meets the expectations for understanding social, economic, and political systems.",
        "{0} demonstrates steady progress in social studies skills and knowledge.",
        "{0} has a solid understanding of historical topics and actively engages in discussions.",
        "{0} shows good knowledge of key events and is able to explain their significance clearly.",
        "{0} demonstrates an understanding of historical concepts but could benefit from further clarification on complex topics.",
        "{0} demonstrates steady progress in grasping historical themes and makes clear connections between events.",
        "{0} has developed a good understanding of social, economic, and political systems, though there is room for growth in applying these concepts.",
        "{0} completes assignments with accuracy and demonstrates a good understanding of the material, but may need support to deepen analysis.",
        "{0} consistently meets grade-level expectations in understanding historical contexts and applying knowledge.",
        "{0} engages in class discussions and is able to articulate an understanding of key historical events and their significance."
    ],
    3: [
        "{0} needs to improve understanding of historical events and their significance.",
        "{0} struggles with analyzing social studies topics and needs additional support.",
        "{0} requires more effort in completing assignments accurately and on time.",
        "{0} needs to engage more with maps and geographic resources to understand concepts.",
        "{0} should participate more in class discussions to enhance understanding of civic concepts.",
        "{0} has difficulty with research skills and needs to seek help when needed.",
        "{0} should work on understanding and connecting social, economic, and political systems.",
        "{0} needs to focus on improving the quality and organization of projects and presentations.",
        "{0} should ask more questions to clarify understanding of the material.",
        "{0} requires more practice and support to meet grade-level expectations in social studies.",
        "{0} struggles to grasp key historical concepts and requires additional support to make connections between events.",
        "{0} needs to improve their ability to analyze historical sources and make meaningful conclusions.",
        "{0} has difficulty organizing historical information and needs guidance to improve research skills.",
        "{0} should seek more support to strengthen their understanding of historical events and their implications.",
        "{0} needs to focus on improving time management to complete assignments and projects more efficiently.",
        "{0} requires additional help to improve their comprehension of social studies material and engage more fully in class discussions.",
        "{0} should make more of an effort to understand the significance of key events and how they relate to current issues.",
        "{0} needs to participate more actively in class to improve understanding and make connections between historical events."
    ]
}