religion_comments = {
    1: [
        "{0} demonstrates a deep understanding of religious concepts and applies them thoughtfully in discussions.",
        "{0} consistently shows respect for diverse beliefs and encourages others with positive reflections and insights.",
        "{0} goes above and beyond in-class assignments, offering unique perspectives on religious themes and values.",
        "{0} shows exceptional enthusiasm and dedication to understanding and living out religious principles.",
        "{0} engages in religious studies with a high degree of empathy, reflecting an admirable grasp of compassion and morality.",
        "{0} consistently demonstrates a strong ability to connect religious teachings to personal life experiences.",
        "{0} frequently engages in deep reflection on the moral lessons in religious texts and brings insightful perspectives to class.",
        "{0} demonstrates an impressive ability to articulate complex religious concepts and make them accessible to others.",
        "{0} applies the values and principles discussed in class in everyday life and encourages others to do the same.",
        "{0} leads by example, showing a deep commitment to living out religious teachings and inspiring others to reflect on their faith.",
        "{0} takes a thoughtful approach to religious discussions and demonstrates a mature understanding of faith and its impact on daily life.",
        "{0} continually seeks to grow in understanding and practicing the principles of faith with sincerity and dedication.",
        "{0} displays an extraordinary commitment to the study and practice of religious teachings, consistently modeling positive behavior.",
        "{0} uses their understanding of religious teachings to guide others in class and outside, fostering a supportive learning environment.",
        "{0} demonstrates a deep sense of spirituality and commitment to ethical living based on religious principles.",
        "{0} engages with religious concepts on a level that demonstrates both intellectual curiosity and personal growth.",
    ],
    2: [
        "{0} regularly participates in class discussions and shows a good understanding of religious teachings.",
        "{0} shows respect for religious diversity and thoughtfully reflects on faith-related topics.",
        "{0} completes assignments on time, displaying a solid grasp of the concepts presented in class.",
        "{0} approaches religious studies sincerely and demonstrates a sound understanding of key principles.",
        "{0} engages in lessons and shows a well-rounded understanding of faith and religious practices.",
        "{0} participates well in class and demonstrates a solid understanding of religious concepts and their relevance.",
        "{0} consistently completes assignments and shows a practical understanding of the teachings and principles of religion.",
        "{0} shows respect for others' beliefs and contributes thoughtfully to discussions about faith and religion.",
        "{0} understands the key religious concepts discussed in class and is developing a stronger sense of how they apply in life.",
        "{0} approaches religious studies with sincerity and shows a growing understanding of key teachings.",
        "{0} reflects thoughtfully on religious topics and is learning to incorporate those reflections into daily life.",
        "{0} has shown good progress in understanding religious principles and is becoming more confident in discussing them.",
        "{0} consistently demonstrates an understanding of the significance of faith in both personal and communal life.",
        "{0} is increasingly able to connect the teachings from class to real-life scenarios in a meaningful way.",
        "{0} is actively working to apply religious values in everyday situations and is progressing well.",
        "{0} often leads class discussions with insightful comments about how faith connects to moral behavior.",
    ],
    3: [
        "{0} struggles to stay engaged in discussions and could benefit from more focus on religious studies.",
        "{0} displays limited understanding of religious concepts and would benefit from additional review and reflection.",
        "{0} needs to show respect and openness towards different beliefs in the classroom setting.",
        "{0} frequently does not complete assignments related to religious studies, impacting comprehension of key topics.",
        "{0} could improve attentiveness and reflection during religious lessons to better grasp core principles.",
        "{0} finds it challenging to grasp key religious concepts and would benefit from more time and focus on studying the material.",
        "{0} is encouraged to engage more deeply in religious discussions to improve their understanding of the subject matter.",
        "{0} needs to be more consistent in completing assignments and engaging with religious studies content to enhance their comprehension.",
        "{0} struggles to show respect for diverse religious views and could benefit from reflection on the importance of inclusivity.",
        "{0} could benefit from additional support and reflection to strengthen their understanding of core religious principles.",
        "{0} would improve their understanding of religious concepts by actively participating in class and completing assigned work on time.",
        "{0} needs to work on being more open-minded and receptive to different religious perspectives discussed in class.",
        "{0} is encouraged to participate more actively in discussions to develop a more comprehensive understanding of religious teachings.",
        "{0} would benefit from additional individual study and attention to the material in order to meet expectations.",
        "{0} is encouraged to approach religious topics with more curiosity and less hesitation to ask questions.",
        "{0} struggles to grasp some of the key themes in religious studies but is showing steady improvement with additional help."
    ]
}