social_comments = {
    1: [
        "{0} demonstrates outstanding communication skills both verbally and non-verbally, contributing positively to group discussions and activities.",
        "{0} exhibits exceptional empathy and kindness towards peers, always willing to lend a helping hand or provide support when needed.",
        "{0} shows great respect for diverse perspectives and backgrounds, fostering an inclusive and welcoming environment for everyone.",
        "{0} consistently displays excellent teamwork abilities, collaborating effectively with classmates to achieve common goals.",
        "{0} maintains strong relationships with peers and teachers, demonstrating exemplary interpersonal skills in all interactions.",
        "{0} exhibits exceptional leadership qualities, inspiring others through their actions and setting a positive example for classmates.",
        "{0} demonstrates remarkable conflict resolution skills, handling disagreements calmly and constructively to reach peaceful resolutions.",
        "{0} shows exemplary manners and etiquette in various social settings, reflecting a high level of social awareness and responsibility.",
        "{0} excels in initiating conversations and builds strong connections with peers, fostering a sense of belonging.",
        "{0} is always willing to help others, creating a supportive and positive environment in class.",
        "{0} consistently demonstrates maturity in social interactions and is a role model for others.",
        "{0} has a natural ability to bring out the best in others, always encouraging collaboration and teamwork.",
        "{0} maintains a positive and friendly attitude, making others feel comfortable and valued.",
        "{0} is an excellent listener, offering thoughtful responses and showing understanding during conversations.",
        "{0} participates confidently in group discussions, offering well-thought-out ideas and insights.",
        "{0} fosters a sense of community and cooperation in the classroom, making everyone feel included."
    ],
    2: [
        "{0} generally communicates effectively with peers and adults, contributing positively to classroom discussions and group activities.",
        "{0} demonstrates kindness and empathy towards others, though occasional reminders may be needed to ensure consistent behavior.",
        "{0} shows respect for diverse perspectives and backgrounds, though may require occasional guidance to fully appreciate differences.",
        "{0} works well with peers in group settings, though may need reminders to actively participate and contribute ideas.",
        "{0} maintains positive relationships with peers and teachers, though occasional conflicts may arise that require assistance to resolve.",
        "{0} shows potential for leadership, occasionally taking initiative in group activities and demonstrating leadership qualities.",
        "{0} handles disagreements with peers appropriately most of the time, though occasional guidance may be needed to improve conflict resolution skills.",
        "{0} demonstrates good manners and etiquette in most social situations, with occasional reminders to be mindful of social norms.",
        "{0} shows great potential in working effectively with others, although sometimes needs reminders to stay engaged.",
        "{0} generally displays a positive attitude towards group activities but can benefit from more active participation.",
        "{0} listens to others and shares ideas but could benefit from further refining how they communicate in group settings.",
        "{0} is considerate of others' opinions but may need occasional guidance to be more assertive in group discussions.",
        "{0} often steps in to mediate small conflicts, helping to keep the group on track and focused.",
        "{0} tends to work well with others and values teamwork, but could benefit from taking on more leadership roles.",
        "{0} occasionally takes the lead in group activities, although they may need encouragement to take initiative more often.",
        "{0} is well-liked by peers and frequently helps create a harmonious environment in class."
    ],
    3: [
        "{0} communicates adequately with peers and adults, though may need encouragement to participate more actively in discussions and activities.",
        "{0} demonstrates some kindness and empathy towards others, but may require reminders to consider the feelings of others consistently.",
        "{0} shows some awareness of diverse perspectives and backgrounds, but may need additional exposure and guidance to fully appreciate differences.",
        "{0} participates in group settings, but may need reminders to collaborate effectively and share ideas with peers.",
        "{0} maintains relationships with peers and teachers, though may struggle at times with conflicts and require assistance to resolve them.",
        "{0} shows potential for leadership, but may need more opportunities and support to develop leadership skills further.",
        "{0} handles disagreements with peers adequately, but may need assistance to improve conflict resolution skills and find peaceful resolutions.",
        "{0} demonstrates basic manners and etiquette in social situations, with occasional reminders to be mindful of appropriate behavior.",
        "{0} struggles to express their ideas clearly in group settings and would benefit from more practice in communication.",
        "{0} occasionally participates but tends to withdraw during group discussions, missing out on opportunities to contribute.",
        "{0} shows limited engagement in group activities and may need additional support to understand the importance of collaboration.",
        "{0} sometimes finds it difficult to work with others, requiring extra encouragement to engage in group tasks.",
        "{0} needs to be reminded regularly to participate in group discussions and offer their input to the team.",
        "{0} has difficulty understanding the perspectives of others and would benefit from more exposure to diverse viewpoints.",
        "{0} could improve social skills by being more mindful of others’ feelings and working on their listening skills.",
        "{0} often needs assistance in resolving conflicts with peers and would benefit from developing stronger conflict resolution skills."
    ]
}